resource_registry:
    OS::TripleO::Controller::Net::SoftwareConfig: ../nic-configs/controller-no-external.yaml
    OS::TripleO::ComputeSriov::Net::SoftwareConfig: ../nic-configs/compute.yaml

  # Reboot before network
  OS::TripleO::Compute::PreNetworkConfig: /usr/share/openstack-tripleo-heat-templates/extraconfig/pre_network/host_config_and_reboot.yaml

parameter_defaults:
    InternalApiNetCidr: 172.17.5.0/24
    StorageNetCidr: 172.17.7.0/24
    StorageMgmtNetCidr: 172.17.8.0/24
    TenantNetCidr: 172.17.6.0/24
    ExternalNetCidr: 10.1.8.0/22
    ControlPlaneSubnetCidr: '24'
    InternalApiAllocationPools: [{'start': '172.17.5.10', 'end': '172.17.5.200'}]
    StorageAllocationPools: [{'start': '172.17.7.10', 'end': '172.17.7.200'}]
    StorageMgmtAllocationPools: [{'start': '172.17.8.10', 'end': '172.17.8.200'}]
    TenantAllocationPools: [{'start': '172.17.6.10', 'end': '172.17.6.200'}]
    ExternalAllocationPools: [{'start': '10.1.10.50','end': '10.1.10.55'}]     
    ExternalInterfaceDefaultRoute: 10.1.11.254
    InternalApiNetworkVlanID: 401
    StorageNetworkVlanID: 402
    StorageMgmtNetworkVlanID: 403
    TenantNetworkVlanID: 404
    ControlPlaneDefaultRoute: 192.0.2.1
    EC2MetadataIp: 192.0.2.1
    ControlPlaneIp: 192.0.2.1
    DnsServers: ["10.11.5.19", "10.10.160.2", "10.5.30.160"]
    OvercloudControlFlavor: control
    OvercloudComputeSriovFlavor: compute

 # Set to empty string to enable multiple external networks or VLANs
  NeutronExternalNetworkBridge: "''"

  # Customize bonding options, e.g. "mode=4 lacp_rate=1 updelay=1000 miimon=100"
  LinuxBondInterfaceOptions: "mode=4 lacp_rate=1 updelay=1000 miimon=100"
  BondInterfaceOvsOptions: "bond_mode=active-backup lacp=active"

  #####
  # SRIOV
  #####

  NeutronTunnelTypes: ""
  NeutronNetworkType: 'vlan'

  NeutronNetworkVLANRanges: "datacentre:1000:2000"

  NeutronPhysicalDevMappings: "sriov1:pcie011,sriov2:pcie012,sriov1:pcie071,sriov2:pcie072"

  NeutronBridgeMappings: 'datacentre:br-all'

  NeutronSupportedPCIVendorDevs: ['8086:1584','8086:154c']

  ComputeParameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=32 iommu=pt intel_iommu=on"
    #TunedProfileName: "cpu-partitioning"
    #IsolCpusList: "1,2,3,4,5,6,7,9,10,17,18,19,20,21,22,23,11,12,13,14,15,25,26,27,28,29,30,31"
    #NovaVcpuPinSet: ['1,2,3,4,5,6,7,9,10,17,18,19,20,21,22,23,11,12,13,14,15,25,26,27,28,29,30,31']
    NovaReservedHostMemory: 4096
    NeutronSriovNumVFs:
      - "pcie011:16"
      - "pcie012:16"
      - "pcie071:16"
      - "pcie072:16"
    NovaPCIPassthrough:
      - devname: "pcie011"
        physical_network: "sriov1"
      - devname: "pcie012"
        physical_network: "sriov2"
      - devname: "pcie071"
        physical_network: "sriov1"
      - devname: "pcie072"
        physical_network: "sriov2"

  # DHCP provide metadata route to VM.
  NeutronEnableIsolatedMetadata: true
  # DHCP always provides metadata route to VM.
  NeutronEnableForceMetadata: true
  # Configure the classname of the firewall driver to use for implementing security groups.
  NeutronOVSFirewallDriver: openvswitch
